"""
MITRE ATT&CK technique mapping for analyzer alerts.

Each alert generated by pcap_analyzer.py is tagged with the most relevant
ATT&CK technique (and parent tactic) so reports can be aligned with the
framework. Lookup is keyed by alert title prefix; when no specific match is
found a category-level fallback is used.

Reference: https://attack.mitre.org/
"""

# Tactic IDs / display names
TACTICS = {
    'TA0043': 'Reconnaissance',
    'TA0001': 'Initial Access',
    'TA0006': 'Credential Access',
    'TA0007': 'Discovery',
    'TA0008': 'Lateral Movement',
    'TA0011': 'Command and Control',
    'TA0010': 'Exfiltration',
    'TA0040': 'Impact',
}


def _t(tid, name, tactic_id):
    return {
        'technique_id': tid,
        'technique_name': name,
        'tactic_id': tactic_id,
        'tactic_name': TACTICS.get(tactic_id, ''),
        'url': f'https://attack.mitre.org/techniques/{tid.replace(".", "/")}/',
    }


# Exact title-prefix mapping. Order matters: longer / more specific first.
TITLE_PREFIX_MAP = [
    # --- Reconnaissance / Discovery ---
    ('Port Scan Detected',                     _t('T1046',     'Network Service Discovery',           'TA0007')),
    ('Horizontal Port Scan',                   _t('T1046',     'Network Service Discovery',           'TA0007')),
    ('ICMP Ping Sweep',                        _t('T1018',     'Remote System Discovery',             'TA0007')),
    ('SNMP Walk Detected',                     _t('T1602.001', 'Data from Configuration Repository: SNMP', 'TA0007')),
    ('Security Scanner User-Agent',            _t('T1595.002', 'Active Scanning: Vulnerability Scanning', 'TA0043')),
    ('HTTP Request Without User-Agent',        _t('T1595',     'Active Scanning',                     'TA0043')),

    # --- Initial Access / Web exploitation ---
    ('HTTP Request to Sensitive/Exploit Path', _t('T1190',     'Exploit Public-Facing Application',   'TA0001')),
    ('HTTP Attack Pattern',                    _t('T1190',     'Exploit Public-Facing Application',   'TA0001')),
    ('Unusual HTTP Method',                    _t('T1190',     'Exploit Public-Facing Application',   'TA0001')),

    # --- Credential Access ---
    ('Password Spraying Detected',             _t('T1110.003', 'Brute Force: Password Spraying',      'TA0006')),
    ('Brute Force Attack Detected',            _t('T1110',     'Brute Force',                         'TA0006')),
    ('LLMNR/NBT-NS Response Activity',         _t('T1557.001', 'LLMNR/NBT-NS Poisoning and SMB Relay', 'TA0006')),
    ('ARP Spoofing Detected',                  _t('T1557.002', 'ARP Cache Poisoning',                 'TA0006')),
    ('Gratuitous ARP Flood',                   _t('T1557.002', 'ARP Cache Poisoning',                 'TA0006')),

    # --- Lateral Movement ---
    ('Internal Lateral Movement Suspected (RDP)',     _t('T1021.001', 'Remote Services: Remote Desktop Protocol', 'TA0008')),
    ('Internal Lateral Movement Suspected (SSH)',     _t('T1021.004', 'Remote Services: SSH',                'TA0008')),
    ('Internal Lateral Movement Suspected (WinRM)',   _t('T1021.006', 'Remote Services: Windows Remote Management', 'TA0008')),
    ('Internal Lateral Movement Suspected (SMB)',     _t('T1021.002', 'Remote Services: SMB/Windows Admin Shares', 'TA0008')),
    ('Internal Lateral Movement Suspected (NetBIOS-SSN)', _t('T1021.002', 'Remote Services: SMB/Windows Admin Shares', 'TA0008')),
    ('Internal Lateral Movement Suspected (Kerberos)', _t('T1558', 'Steal or Forge Kerberos Tickets',          'TA0006')),
    ('Internal Lateral Movement Suspected (RPC',      _t('T1021.003', 'Remote Services: Distributed Component Object Model', 'TA0008')),
    ('Internal Lateral Movement Suspected',           _t('T1021',     'Remote Services',                     'TA0008')),
    ('External IP Accessing SMB',                     _t('T1021.002', 'Remote Services: SMB/Windows Admin Shares', 'TA0008')),

    # --- Command and Control ---
    ('Beaconing Behavior Detected (Periodic Signal)', _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
    ('Beaconing Behavior Detected',                   _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
    ('Known Malicious JA3 Fingerprint',               _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('Possible DGA Domain Activity',                  _t('T1568.002', 'Dynamic Resolution: Domain Generation Algorithms', 'TA0011')),
    ('Fast-Flux Domain Suspected',                    _t('T1568.001', 'Dynamic Resolution: Fast Flux DNS',   'TA0011')),
    ('NXDOMAIN Spike Detected',                       _t('T1568.002', 'Dynamic Resolution: Domain Generation Algorithms', 'TA0011')),
    ('Queries to Suspicious TLD',                     _t('T1568',     'Dynamic Resolution',                  'TA0011')),
    ('DNS Tunneling Suspected',                       _t('T1071.004', 'Application Layer Protocol: DNS',     'TA0011')),
    ('Cumulative DNS Exfiltration Suspected',         _t('T1048.003', 'Exfiltration Over Unencrypted Protocol', 'TA0010')),
    ('DNS-over-TLS (DoT) Connection',                 _t('T1071.004', 'Application Layer Protocol: DNS',     'TA0011')),
    ('Suspicious TLS SNI',                            _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
    ('TLS ClientHello Without SNI',                   _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('Obsolete TLS Version',                          _t('T1573.001', 'Encrypted Channel: Symmetric Cryptography', 'TA0011')),
    ('Suspicious Port',                               _t('T1571',     'Non-Standard Port',                   'TA0011')),

    # --- Exfiltration ---
    ('Possible Data Exfiltration (Upload Volume)',    _t('T1048',     'Exfiltration Over Alternative Protocol', 'TA0010')),
    ('Sustained Exfiltration Ratio',                  _t('T1029',     'Scheduled Transfer',                  'TA0010')),
    ('Possible ICMP Tunneling',                       _t('T1095',     'Non-Application Layer Protocol',      'TA0011')),
    ('Connection to File-Share / Paste Service',      _t('T1567.002', 'Exfiltration Over Web Service: Cloud Storage', 'TA0010')),
    ('SMB Traffic to External IP',                    _t('T1048',     'Exfiltration Over Alternative Protocol', 'TA0010')),

    # --- Cleartext / weak protocols ---
    ('Insecure Protocol: FTP',                        _t('T1071',     'Application Layer Protocol',          'TA0011')),
    ('Insecure Protocol: Telnet',                     _t('T1071',     'Application Layer Protocol',          'TA0011')),
    ('Cleartext Credentials',                         _t('T1040',     'Network Sniffing',                    'TA0006')),

    # --- MAC / spoofing ---
    ('IP with Multiple MAC Addresses',                _t('T1557',     'Adversary-in-the-Middle',             'TA0006')),
    ('External IP with Multiple MAC Addresses',       _t('T1557',     'Adversary-in-the-Middle',             'TA0006')),

    # --- Behavioral baseline deviations ---
    ('First-Seen External Destination',               _t('T1071',     'Application Layer Protocol',          'TA0011')),
    ('New Protocol on Known Host',                    _t('T1071',     'Application Layer Protocol',          'TA0011')),
    ('Outbound Volume Surge vs Baseline',             _t('T1048',     'Exfiltration Over Alternative Protocol', 'TA0010')),
    ('Inbound Volume Surge vs Baseline',              _t('T1105',     'Ingress Tool Transfer',               'TA0011')),
    ('New Internal Host Active on Network',           _t('T1078',     'Valid Accounts',                      'TA0001')),
    ('Activity in Unusual Time Window',               _t('T1078',     'Valid Accounts',                      'TA0001')),

    # --- Statistical / ML ---
    ('High-Entropy Payload on Cleartext Port',        _t('T1572',     'Protocol Tunneling',                  'TA0011')),
    ('Anomalous Flow (Isolation Forest)',             _t('T1071',     'Application Layer Protocol',          'TA0011')),

    # --- First-seen (correlation) ---
    ('New MAC Address on Network',                    _t('T1078',     'Valid Accounts',                      'TA0001')),
    ('New JA3 (TLS Client Fingerprint)',              _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('New JA3S (TLS Server Fingerprint)',             _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('New JA4 (TLS Client Fingerprint)',              _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('New JA4S (TLS Server Fingerprint)',             _t('T1573',     'Encrypted Channel',                   'TA0011')),
    ('New JA4H (HTTP Client Fingerprint)',            _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
    ('New HASSH (SSH Client Fingerprint)',            _t('T1021.004', 'Remote Services: SSH',                'TA0008')),
    ('New HASSH-Server (SSH Server Fingerprint)',     _t('T1021.004', 'Remote Services: SSH',                'TA0008')),
    ('New TLS SNI Observed',                          _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
    ('New HTTP Host Observed',                        _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011')),
]

# Category fallback (used when no title prefix matches).
CATEGORY_FALLBACK = {
    'scan':        _t('T1046', 'Network Service Discovery',          'TA0007'),
    'port':        _t('T1571', 'Non-Standard Port',                  'TA0011'),
    'arp':         _t('T1557.002', 'ARP Cache Poisoning',            'TA0006'),
    'mac':         _t('T1557', 'Adversary-in-the-Middle',            'TA0006'),
    'dns':         _t('T1071.004', 'Application Layer Protocol: DNS', 'TA0011'),
    'protocol':    _t('T1071', 'Application Layer Protocol',         'TA0011'),
    'smb':         _t('T1021.002', 'Remote Services: SMB/Windows Admin Shares', 'TA0008'),
    'beaconing':   _t('T1071.001', 'Application Layer Protocol: Web Protocols', 'TA0011'),
    'brute_force': _t('T1110', 'Brute Force',                        'TA0006'),
    'tls':         _t('T1573', 'Encrypted Channel',                  'TA0011'),
    'http':        _t('T1190', 'Exploit Public-Facing Application',  'TA0001'),
    'exfil':       _t('T1048', 'Exfiltration Over Alternative Protocol', 'TA0010'),
    'lateral':     _t('T1021', 'Remote Services',                    'TA0008'),
    'behavioral':  _t('T1071', 'Application Layer Protocol',         'TA0011'),
    'anomaly':     _t('T1071', 'Application Layer Protocol',         'TA0011'),
    'first-seen':  _t('T1078', 'Valid Accounts',                     'TA0001'),
    # Incidents are kill-chains; we leave the technique generic but flag the
    # tactic as Impact so they sort to the top of executive reports.
    'incident':    _t('T1078', 'Valid Accounts',                     'TA0040'),
    'user-rule':   _t('T1071', 'Application Layer Protocol',         'TA0011'),
}


def lookup_attack(alert):
    """Return MITRE ATT&CK metadata dict for an alert (or None if no match)."""
    title = (alert.get('title') or '').strip()
    for prefix, mapping in TITLE_PREFIX_MAP:
        if title.startswith(prefix):
            return mapping
    return CATEGORY_FALLBACK.get(alert.get('category'))


def annotate_alerts(alerts):
    """Mutate alert list, adding `mitre_attack` block to each alert.

    If an alert already carries a `mitre_attack` block (detector set it
    inline — used by CobaltStrikeDetector, ExploitPayloadDetector etc. to
    pick a finer-grained technique than the title-prefix table would), we
    leave it untouched. The fallback path only fills in alerts that lack
    one entirely.
    """
    for alert in alerts:
        if alert.get('mitre_attack'):
            continue
        info = lookup_attack(alert)
        if info:
            alert['mitre_attack'] = info
    return alerts
